#!/bin/bash
set -o errexit

ssh-add
echo "Compiling..."
npm run build-dist
echo "Uploading..."
scp dist/LapisAzurai.zip threewestwinds.com:LapisAzurai.zip
echo "Unpacking..."
ssh threewestwinds.com "cd LapisAzurai && rm -rf * && mv ../LapisAzurai.zip . && unzip -q LapisAzurai.zip"
echo "Deployed."
