export var startingGame = {
  version: 0,
  day: 0,
  scroll: 0,
  chapter: 'Ch1',
  cargo: [],
  damage: 0,
  availableCargo: [],
  jobFocus: '',
  jobSearch: {},
  showHelp: true,
  map: {
    from: 'Vailia',
    to: '',
    distance: 0,
    delay: 0,
  },
  lastTravelEvent: 0,
  lastStorm: 0,
  reputation: {
    Vailia: 5,
  },
  people: {
    Natalie: {
      xp: 0,
      skills: {},
    },
    James: {
      xp: 0,
      skills: {},
    },
  },
  history: {
    Intro: 0,
  },
};

export var goods = {
  'Alchemical Reagents': [12, 7],
  Allspice: [8, 6],
  Almonds: [3, 3],
  Amber: [5, 8],
  Anchors: [2, 2],
  Apples: [2, 3],
  'Apple Vinegar': [4, 4],
  Apricots: [3, 3],
  Bacon: [4, 3],
  Basil: [7, 7],
  Beer: [4, 5],
  Brandy: [6, 7],
  'Brass fittings': [5, 8],
  'Bronze Sculpture': [12, 4],
  Butter: [4, 2],
  Candles: [4, 9],
  Camphor: [6, 6],
  Canvas: [4, 3],
  Carpet: [5, 3],
  Cashews: [4, 4],
  'Cast Iron Cookware': [3, 10],
  Chains: [3, 8],
  Chalk: [4, 4],
  Chamomile: [9, 5],
  Charcoal: [8, 4],
  Chickens: [3, 2],
  Cheese: [5, 4],
  'Clockwork Machinery': [3, 10],
  Clothing: [3, 4],
  Cloves: [8, 6],
  Coffee: [9, 10],
  'Composite Bows': [5, 12],
  Copper: [2, 4],
  Coral: [2, 5],
  Cork: [6, 6],
  Cotton: [2, 3],
  Cumin: [3, 10],
  Dates: [3, 3],
  'Decorative Stone': [5, 5],
  'Expensive Pottery': [7, 9],
  Eucalyptus: [3, 5],
  'Fashionable Clothing': [4, 10],
  Feathers: [4, 7],
  Figs: [2, 4],
  'Fine Furniture': [4, 3],
  'Fine Wine': [7, 12],
  'Fish Hooks': [4, 7],
  Flour: [4, 4],
  Frankincense: [5, 10],
  'Fruit Jam': [4, 4],
  Furs: [7, 5],
  Garlic: [3, 4],
  'Glass Beads': [6, 8],
  'Glass Jars': [3, 8],
  Gold: [7, 9],
  'Gold Jewelry': [7, 12],
  'Hatchets and Saws': [3, 8],
  Hats: [4, 8],
  Helmets: [4, 9],
  Honey: [5, 6],
  Indigo: [10, 6],
  Ink: [3, 10],
  Iron: [5, 3],
  Ivory: [4, 11],
  Jasmine: [6, 7],
  'Kitchen Utensils': [3, 5],
  Lavender: [3, 5],
  Lead: [4, 4],
  Leather: [7, 4],
  Lemons: [4, 2],
  Lilac: [5, 6],
  Liquorice: [5, 4],
  Linen: [4, 10],
  Limestone: [2, 4],
  'Live Cattle': [2, 3],
  'Live Goats': [2, 3],
  Lumber: [2, 2],
  'Maiden Tea': [2, 9],
  Masts: [2, 4],
  Matches: [3, 9],
  Mint: [6, 4],
  'Mirrors and Lenses': [6, 11],
  Mulberries: [4, 3],
  Mercury: [7, 11],
  Mustard: [6, 4],
  Myrrh: [10, 8],
  'Nails and Tacks': [5, 5],
  Nails: [4, 5],
  Nutmeg: [4, 8],
  Oars: [5, 6],
  Olives: [5, 5],
  'Olive Oil': [3, 10],
  Onions: [3, 3],
  Opal: [7, 8],
  Oranges: [4, 3],
  Paper: [5, 7],
  Papyrus: [4, 5],
  Peanuts: [2, 4],
  Pearls: [5, 11],
  Pepper: [4, 12],
  'Pickled Fish': [2, 3],
  Pickles: [3, 6],
  Raisins: [2, 4],
  'Red Pepper': [4, 9],
  Rope: [3, 7],
  Rosehips: [3, 6],
  'Rough Clothing': [3, 8],
  Rubber: [3, 10],
  Ruby: [6, 10],
  'Safflower Oil': [4, 5],
  Saffron: [9, 10],
  Sage: [8, 6],
  Salt: [3, 9],
  Sandalwood: [4, 10],
  Sapphires: [8, 8],
  'Self Bows': [5, 8],
  Silver: [5, 5],
  'Smoked Fish': [3, 3],
  'Smoked Game Meat': [4, 4],
  Soap: [2, 5],
  Spears: [5, 12],
  'Steel Tools': [6, 11],
  'Steel Wire': [3, 5],
  'Stone Sculpture': [6, 3],
  Sulfur: [4, 9],
  Swords: [5, 12],
  Tar: [4, 4],
  'Tea Leaves': [3, 5],
  Tin: [3, 5],
  Topaz: [6, 7],
  Turmeric: [5, 9],
  Vanilla: [7, 7],
  'Veined Marble': [3, 2],
  Walnuts: [4, 5],
  Wax: [4, 10],
  Wheat: [3, 4],
  Woad: [4, 7],
  'Wood Carvings': [5, 7],
  Wool: [2, 4],
  Wormwood: [4, 4],
};
